---
- hosts: all
  become: true
  tasks:
    - name: installing http server
      yum:
        name: httpd
        state: latest

    - name: start the apache httpd server
      service:
        name: httpd
        state: started
        enabled: true
...



