---
- hosts: all
  become: true
  tasks:
    - name: installing http server
      yum:
        name: httpd
        state: latest
    - name: copy index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: start the apache httpd server
      service:
        name: httpd
        state: started
        enabled: true

---
- hosts: all
  become: true
  tasks:
    - name: installing http server
      yum:
        name: httpd
        state: latest

    - name: start the apache httpd server
      service:
        name: httpd
        state: started
        enabled: true
---

